name: Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['dev', 'main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install mustache (to update the date)
        run: gem install mustache --user-install

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: creates output
        run: sh ./build.sh

      - name: Pushes to another repository
        if: github.event_name == 'push'
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: 'output'
          destination-github-username: SujeongJeong
          destination-repository-name: KBE5_HALO_FE
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: dev
